### ISSUE TITLE
Allow select/cut/copy/paste of subproofs

### ISSUE THREAD

**Issue by rzach** [gleachkr/ProofJS#1]
It would be nice to be able to select, cut, copy, and paste entire subproofs. (Perhaps by clicking on the last inference line in the subproof to select, and Ctrl+C,V,X for copy/paste/cut.

**Comment by gleachkr** [comment]
This is 90% addressed by b8158de. As far as I can tell, there's no really good cross-browser way to access the system clipboard from the browser using JavaScript (there's something in the spec, but it is inconsistently implemented at the moment).

So, for the moment, a copied proof is stored in a regular variable. You can copy paste within a page, but you can't copy-paste across windows or navigating from page to page, or into a text document to store for later. I'll experiment with the localStorage API in the browser to see if the first two cases can be handled. As far as I can tell the last case would require a pretty complicated workaround that I think I would like to avoid.

Also, used Ctrl-Shift rather than Ctrl, so that you can do a regular copy-paste or a subproof copy-paste.

**Comment by rzach** [comment]
Cool. Maybe it would be good enough to be able to download and upload (the selected subtree) as a JSON file? Then at least it's possible to save one's work and return to it later. (It would also make it possible for someone to copy someone else's tree, of course, but perhaps that could be prevented by storing an encrypted version of userid + save time, and only accept an upload if the user id matches.)

**Comment by gleachkr** [comment]
We now have persistent cut/paste within a given browser using localStorage, via c681398. I think you're right that the remaining use case might be something to handle with some kind of save/restore functionality. Maybe a separate issue for that?
